Feature 63 page drafts
Metatavu/wordpress-sptv pull request #66
Opened 2022-05-03 09:26 UTC by platonovsimeon

Resolves #63

2022-05-03 12:17 UTC, anttileppa requested changes

2022-05-03 12:17 UTC, anttileppa commented on page-drafts/page-drafts.php
> +  function createDrafts($new_index_items, $template_type, $new_sync_time) {
snake cases?

2022-05-03 12:17 UTC, anttileppa commented on settings/settings-ui.php
> +      private function addVersionDropdown() {
Add docs

2022-05-03 12:17 UTC, anttileppa commented on settings/settings-ui.php
> +      private function addTemplateDropdown($name, $title, $templates) {
Add docs

2022-05-05 07:02 UTC, anttileppa requested changes

2022-05-05 07:02 UTC, anttileppa commented on page-drafts/page-drafts.php
> +          $newIndexItems = $this->getNewIndexItems('v11-service', 'organizationIds', $lastSyncTime);
Version should come from the settings

2022-05-05 07:02 UTC, anttileppa commented on page-drafts/page-drafts.php
> +          $newIndexItems = $this->getNewIndexItems('v11-servicelocation-service-channel', 'organizationId', $lastSyncTime);
Version should come from the settings

2022-05-05 07:02 UTC, anttileppa commented on settings/settings-ui.php
> +      public function createVersionDropDownUI($opts) {
Add docs

2022-05-05 14:42 UTC, platonovsimeon commented on page-drafts/page-drafts.php
> +                    $organizationFieldName => array_values(Settings::getOrganizationIds())[0]
Fixed

2022-05-05 14:43 UTC, platonovsimeon commented on page-drafts/page-drafts.php
> +          $newIndexItems = $this->getNewIndexItems('v11-service', 'organizationIds', $lastSyncTime);
Fixed

2022-05-05 14:43 UTC, platonovsimeon commented on page-drafts/page-drafts.php
> +          $newIndexItems = $this->getNewIndexItems('v11-servicelocation-service-channel', 'organizationId', $lastSyncTime);
Fixed

2022-05-05 14:45 UTC, platonovsimeon commented on settings/settings-ui.php
> +      public function createVersionDropDownUI($opts) {
Fixed

2022-05-07 08:41 UTC, merged